build: attempt different approach in wait timeout

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,35 +57,31 @@ jobs:
     - name: Run Makefile 'all' task
       run: |
         make \
-          MODE=github \
           MARIADB_TAG=$MARIADB_TAG \
           WORDPRESS_TAG=$WORDPRESS_TAG \
           NODE_TAG=$NODE_TAG
 
     #https://cardinalby.github.io/blog/post/github-actions/implementing-deferred-steps/
-    - name: Wait for WordPress setup to complete
-      run: |
-        timeout=300
-        while [ $timeout -gt 0 ]; do
-          docker compose exec wordpress test -f /bitnami/wordpress/wp-config.php && break
-          echo "Waiting for wp-config.php ($timeout seconds left)..."
-          sleep 5
-          timeout=$((timeout - 5))
-        done
-        [ $timeout -gt 0 ] || { echo "Error: Timeout reached, wp-config.php not found"; exit 1; }
+    #- name: Wait for WordPress setup to complete
+    #  run: |
+    #    timeout=300
+    #    while [ $timeout -gt 0 ]; do
+    #      docker compose exec wordpress test -f /bitnami/wordpress/wp-config.php && break
+    #      echo "Waiting for wp-config.php ($timeout seconds left)..."
+    #      sleep 5
+    #      timeout=$((timeout - 5))
+    #    done
+    #    [ $timeout -gt 0 ] || { echo "Error: Timeout reached, wp-config.php not found"; exit 1; }
 
-    - name: Run Makefile 'install-*' tasks
+    - name: Run Makefile 'install' task
       run: |
-        make install-node install-wordpress \
-          MODE=github \
-          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
+        make install \
+          MARIADB_TAG=$MARIADB_TAG \
+          WORDPRESS_TAG=$WORDPRESS_TAG \
+          NODE_TAG=$NODE_TAG
 
     - name: Run Makefile 'test' task
-      run: |
-        make test \
-          MODE=github
+      run: make test
           
     - name: Run Makefile 'down' task
-      run: |
-        make down \
-          MODE=github
+      run: make down
